### ISSUE TITLE
Nits: two minor thoughts in readme

### ISSUE THREAD

**Issue by breck7** [justjake/ktree#1]
I'm not too familiar with Kotlin so not sure if these nits are relevant.

1. "type" property

```
"type": "root" 
```
I don't think this is needed in the canonical interface? I think we just need children and cells. Any node you parse becomes type "root". I guess also a root would not have "cells", so you could perhaps infer if it was of type "root" by the lack of a cells property? So perhaps you could have 2 separate interfaces:

```
interface ParentTreeNode {
 children: ChildNode
}
interface ChildTreeNode extends ParentTreeNode {
 cells: string[]
}
```
Or merge them and denote whether something is Child or Parent by absence of a "cells" member.

2. super nit: empty children

```
"children": []
```

Not sure if Kotlin has optional/union types, but for empty children in TypeScript I just drop it in the serialization.

ktree readme is great. Really clear.

**Comment by justjake** [comment]
I fixed the JSON issues in commit https://github.com/justjake/ktree/commit/bac7bb8eb49f2232d35436fd17f49c24f1fe6beb,
but I didn't update the README afterwards. Thanks for the pointers.

**Comment by justjake** [comment]
Fixed in https://github.com/justjake/ktree/commit/171b4f92925c089a94504260fbc06dc9b0acd18d
